apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: devops-challenge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo  # Disponível no GKE por padrão
  resources:
    requests:
      storage: 5Gi
