apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: devops-challenge
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: devops-challenge
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
  type: ClusterIP  # Acesso apenas interno (prometheus scrape)
