apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: devops-challenge
  labels:
    app: app2
spec:
  selector:
    app: app2
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP  # Acesso apenas interno (via nginx)
